pub mod attestation;
pub mod block;
pub mod block_v2;
pub mod randao_reveal;
pub mod aggregate_and_proof;
pub mod aggregation_slot;
pub mod deposit;
pub mod sync_committee_message;
pub mod sync_committee_selection_proof;
pub mod contribution_and_proof;
// pub mod validator_registration;
